// Imports Globally Applied Styles
import '../styles/globals.scss'

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

// Setup Fonts
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mikkels Boilerplate',
  description: 'Generated by create next app',
}

// Remember to set language on html

export default function RootLayout({ children }) {
  return (
    <html lang="da-DK">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
